# Generated by Django 3.1.2 on 2020-10-02 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portfoio',
            new_name='Portfolio',
        ),
    ]
