# Generated by Django 3.1.2 on 2021-01-07 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20210107_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='thumbnail',
        ),
    ]
