# Generated by Django 3.1.2 on 2021-01-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20210115_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='goods/thumbnail'),
        ),
    ]
