# Generated by Django 3.1.2 on 2021-01-18 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20210115_0050'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Goods',
            new_name='Item',
        ),
    ]
